# -*- coding: utf-8 -*-
THEMES = {
    'tech_blue': {
        'name': '科技蓝',
        'sidebar_bg': '#0f2b5e', 'sidebar_hover': '#1a3d7a', 'sidebar_active': '#1e6fff',
        'sidebar_text': '#ffffff', 'topbar_bg': '#1e6fff', 'topbar_text': '#ffffff',
        'main_bg': '#f5f7fa', 'card_bg': '#ffffff', 'card_border': '#e4e7ed',
        'text_primary': '#303133', 'text_secondary': '#606266', 'text_hint': '#909399',
        'primary': '#1e6fff', 'primary_hover': '#0052d9', 'success': '#67c23a',
        'warning': '#e6a23c', 'danger': '#f56c6c', 'info': '#909399',
        'table_header_bg': '#1e6fff', 'table_header_text': '#ffffff',
        'table_stripe': '#f5f7fa', 'font_family': 'Microsoft YaHei UI',
        'font_size_normal': 12, 'font_weight': 'bold',
    },
    'minimal_white': {
        'name': '极简白',
        'sidebar_bg': '#ffffff', 'sidebar_hover': '#f5f7fa', 'sidebar_active': '#ecf5ff',
        'sidebar_text': '#606266', 'topbar_bg': '#ffffff', 'topbar_text': '#303133',
        'main_bg': '#fafafa', 'card_bg': '#ffffff', 'card_border': '#ebeef5',
        'text_primary': '#303133', 'text_secondary': '#606266', 'text_hint': '#909399',
        'primary': '#409eff', 'primary_hover': '#66b1ff', 'success': '#67c23a',
        'warning': '#e6a23c', 'danger': '#f56c6c', 'info': '#909399',
        'table_header_bg': '#f5f7fa', 'table_header_text': '#303133',
        'table_stripe': '#fafafa', 'font_family': 'Microsoft YaHei UI',
        'font_size_normal': 12, 'font_weight': 'bold',
    },
    'dark_mode': {
        'name': '深邃黑',
        'sidebar_bg': '#0f1020', 'sidebar_hover': '#1a1b35', 'sidebar_active': '#0084ff',
        'sidebar_text': '#a0a3b0', 'topbar_bg': '#16213e', 'topbar_text': '#e0e0e0',
        'main_bg': '#1a1a2e', 'card_bg': '#2a2b3d', 'card_border': '#3a3b55',
        'text_primary': '#e0e0e0', 'text_secondary': '#a0a3b0', 'text_hint': '#707280',
        'primary': '#00d4ff', 'primary_hover': '#00b8e6', 'success': '#00ff88',
        'warning': '#ffcc00', 'danger': '#ff5577', 'info': '#707280',
        'table_header_bg': '#1e2845', 'table_header_text': '#00d4ff',
        'table_stripe': '#1f2035', 'font_family': 'Microsoft YaHei UI',
        'font_size_normal': 12, 'font_weight': 'bold',
    },
    'fresh_cyan': {
        'name': '活力青',
        'sidebar_bg': '#0f4c3a', 'sidebar_hover': '#156a50', 'sidebar_active': '#00b894',
        'sidebar_text': '#ffffff', 'topbar_bg': '#00b894', 'topbar_text': '#ffffff',
        'main_bg': '#f0faf7', 'card_bg': '#ffffff', 'card_border': '#d0e8e0',
        'text_primary': '#303133', 'text_secondary': '#606266', 'text_hint': '#909399',
        'primary': '#00b894', 'primary_hover': '#00a085', 'success': '#00b894',
        'warning': '#fdcb6e', 'danger': '#e17055', 'info': '#81ecec',
        'table_header_bg': '#00b894', 'table_header_text': '#ffffff',
        'table_stripe': '#f0faf7', 'font_family': 'Microsoft YaHei UI',
        'font_size_normal': 12, 'font_weight': 'bold',
    },
    'business_gray': {
        'name': '商务灰',
        'sidebar_bg': '#e8eaed', 'sidebar_hover': '#d0d5dc', 'sidebar_active': '#2c3e50',
        'sidebar_text': '#34495e', 'topbar_bg': '#2c3e50', 'topbar_text': '#ffffff',
        'main_bg': '#f4f5f7', 'card_bg': '#ffffff', 'card_border': '#d0d5dc',
        'text_primary': '#2c3e50', 'text_secondary': '#5d6d7e', 'text_hint': '#95a5a6',
        'primary': '#2c3e50', 'primary_hover': '#1a252f', 'success': '#27ae60',
        'warning': '#f39c12', 'danger': '#e74c3c', 'info': '#7f8c8d',
        'table_header_bg': '#2c3e50', 'table_header_text': '#ffffff',
        'table_stripe': '#f8f9fa', 'font_family': 'Microsoft YaHei UI',
        'font_size_normal': 12, 'font_weight': 'bold',
    },
}
DEFAULT_THEME = 'tech_blue'

def get_theme(k): return THEMES.get(k, THEMES[DEFAULT_THEME])
def get_all_themes(): return [(k, v['name']) for k, v in THEMES.items()]
